title: Breast Cancer Predictor  
description: AI-powered diagnosis tool for breast cancer detection ðŸ§¬  
remote_theme: pages-themes/cayman@v0.2.0  
plugins:
  - jekyll-remote-theme  
markdown: kramdown  
